version: '3.8'
services:
  nest-api:
    container_name: ${NEST_CONTAINER_NAME}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${NEST_PORT_EXTERNAL}:${NEST_PORT_INTERNAL}'
    depends_on:
      - postgres
    env_file:
      - .env.docker

  postgres:
    image: postgres:15
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    ports:
      - '${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}'
    env_file:
      - .env.docker
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: ${VOLUME_NAME}
